name: Build and Deploy to GCP

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: qwiklabs-gcp-03-b71cdde17bdc
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Stop JAR on GCP Compute Engine if running
        run: |
          gcloud compute ssh --zone=asia-south1-c student-00-4709b6b8eb38@demo123 --command="if pgrep -f ems-0.0.1-SNAPSHOT.jar; then pkill -f ems-0.0.1-SNAPSHOT.jar; else echo 'No process found'; fi"

      - name: Copy JAR to GCP Compute Engine
        run: |
          gcloud compute scp --zone=asia-south1-c target/ems-0.0.1-SNAPSHOT.jar student-00-4709b6b8eb38@demo123:~

      - name: Start JAR on GCP Compute Engine
        run: |
          gcloud compute ssh --zone=asia-south1-c student-00-4709b6b8eb38@demo123 --command="screen -dm java -jar ~/ems-0.0.1-SNAPSHOT.jar"
          sleep 20
          gcloud compute ssh --zone=asia-south1-c student-00-4709b6b8eb38@demo123 --command="if pgrep -f ems-0.0.1-SNAPSHOT.jar > /dev/null; then echo 'Server started'; else echo 'Server failed to start'"
          
